services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"    # porta para o broker
      - "15672:15672"  # porta da UI de admin
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
